### ISSUE TITLE
encoding feature breaks API

### ISSUE THREAD

**Issue by stbuehler** [tafia/quick-xml#180]
Hi,

the way features work in cargo is that any crate in your dependency tree can enable additional features for its dependencies, and each dependency ("crate") is only compiled once with all features merged; thus they must only add additional "APIs" without breaking what was before.

I.e. enabling the `encoding` feature should provide new structs and functions (or just improve existing ones without changing their signature).

Also the `reader::Decoder` struct is not public and not documented, but `Reader::decoder()` is... I guess either both or none should be public.

**Comment by tafia** [comment]
You are right, this is an oversight on my side.

**Comment by pcleavelin** [comment]
I believe this issue should be re-opened due to [this commit](https://github.com/tafia/quick-xml/commit/ec63ed086e2b58ae50eaf421eed37619bf33fc65) as it still breaks the API when enabling the `encoding` feature. 

This is causing issues on a project I work on that relies on `Attribute::unescape_value` existing when including a dependency that enables `encoding` internally.

**Comment by Mingun** [comment]
I think, that we shouldn't. The current situation removes some functions if `encoding` feature is enabled. Yes, that is not a good thing, because _another_ crate in your dependency tree can enable that feature and your code that uses this function will stop to compile. In that case just do not use those functions if you unsure if something can enable them. Definitely it is bad idea use it in the library code, but you could find them useful in application code. I'll accept a PR that will add an explicit attention to docstrings of that functions about that nuance.

**Comment by pcleavelin** [comment]
Maybe I'm missing context on why the function is removed with `encoding` in the first place. Is there some state that isn't updated if you were to use it? (Forgive me I'm not familiar with this codebase).

**Comment by Mingun** [comment]
Because those set of functions uses UTF-8 encoding to convert internal `&[u8]` to strings. That is possible, because when `encoding` feature is not enabled we always assume that documents in UTF-8
