### ISSUE TITLE
serdes enum representations is not working as expected

### ISSUE THREAD

**Issue by Dgame** [tafia/quick-xml#190]
This works as expected:

```Rust
#[derive(Debug, Serialize, Deserialize)]
struct Foo {
    id: u32,
    kind: String
}

#[derive(Debug, Serialize, Deserialize)]
struct Root {
    bar: Foo
}

let xml = r#"<root><bar kind="Foo"><id>42</id></bar></root>"#;
let root: Root = quick_xml::de::from_str(xml).unwrap();
```

But this:

```Rust
#[derive(Debug, Serialize, Deserialize)]
#[serde(tag = "kind")]
enum Bar {
    Foo {
        id: u32,
    }
}

#[derive(Debug, Serialize, Deserialize)]
struct Root {
    bar: Bar
}

let xml = r#"<root><bar kind="Foo"><id>42</id></bar></root>"#;
let root: Root = quick_xml::de::from_str(xml).unwrap();
```

fails with 
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("invalid type: map, expected u32")', src/libcore/result.rs:1165:5

Why is that?

**Comment by tafia** [comment]
Indeed it looks like serde's tag option for enums is not supported.
This is something I need to work on.

**Comment by Mingun** [comment]
This behaviour is consequence of https://github.com/serde-rs/serde/issues/1183 and usage of `deserialize_any` under the hood for deserializing internally tagged enums.

XML deserializer parses any `deserialize_any` requests as maps when element contains internal elements and this is correct for generic deserialization. When deserialized type uses special hinted method (`deserialize_str`, etc) the deserializer is able to perform necessary conversion. The problem is that in this case that hint is lost, because type deserialized not from our deserializer, but from internal serde deserializer:
- Internal serde deserializer requests any data from our deserializer and stores it. In that place original type hint is lost
- Deserialized type requests data from internal serde deserializer, using hinted method, but it is able to perform only very limited conversions between types (and of course can't convert map to string), so it's returns type, that our deserialzier choose to return to very generic `deserialize_any` request.

This situation can't be solved only from deserializer side, this requires change of how serde derive the `Deserialize` implementation

**Comment by Mingun** [comment]
As explained, it is a serde bug, we can not do anything with it at deserializer level.
