### ISSUE TITLE
Is this result expected when serializing in the enum type?

### ISSUE THREAD

**Issue by ImJeremyHe** [tafia/quick-xml#283]
Thanks for your effort. It is awesome that using serde to serialize or deserialize the xml.
There are some differences in serializing enum type between the output in quick_xml and that in serde_json. 
```rs
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug)]
enum Type {
    Foo,
    Bar,
}

#[derive(Serialize, Deserialize, Debug)]
struct A {
    pub member: Type
}

fn main() {
    let data = A {member: Type::Foo};
    let json_result = serde_json::to_string(&data).unwrap();
    println!("{:?}", json_result);
    let xml_result = quick_xml::se::to_string(&data).unwrap();
    println!("{:?}", xml_result);
}

```
The output of this code is
```
"{\"member\":\"Foo\"}"
"<A><Foo/></A>"
```

Is this result is expected? I think it should be 
```xml
"<A member="Foo"><A/>"
```

**Comment by bachp** [comment]
I was also confused by this result as I was also expecting `<A member="Foo"><A/>` as a result. Is there a way to get this?

**Comment by fwcd** [comment]
I think the issue is that all unit variants (`Type::Foo` and `Type::Bar` in this example) are serialized as self-closed tags, i.e. `<Foo/>` and `<Bar/>` (see [here](https://github.com/tafia/quick-xml/blob/2dbb753ff0d06155d787cf894d0b0d1ce2568361/src/se/mod.rs#L235)).

If we have an enum that consists _only_ of unit variants, like `Type` in your example, we may want to serialize it as a string instead, i.e. use `write_primitive` instead of `write_self_closed`. Unfortunately, serde doesn't tell us if we are dealing with such an enum, AFAICT. We could of course always serialize unit variants as strings, that may however lead to potentially surprising results on an enum that contains both variants with and without parameters:

```rust
enum OptionInt {
    None,                 // -> "None" instead of "<None/>"
    Some { value: i32 }   // -> "<Some value=.../>"
}
```
