### ISSUE TITLE
$unflatten doesn't work with empty element and Vec

### ISSUE THREAD

**Issue by mohe2015** [tafia/quick-xml#315]
The two bugs are fixed! I found another one though: https://github.com/mohe2015/quick-xml-bugs/commit/8dfcb238406143102664fc186480758786423d90. I would expect to get an empty Vec if I'm not mistaken.

_Originally posted by @mohe2015 in https://github.com/tafia/quick-xml/issues/306#issuecomment-898941176_

**Comment by Mingun** [comment]
If I correctly understand you, you found this situation:
```rust
type Sequence = Vec<()>;
struct List {
  item: Sequence,
}
```
and you expect that that XML would be deserialized:
```xml
<any-tag>
</any-tag>
```
Unfortunately, we cannot distinguish this from the situation when `item` field is required, because `List` type has no access to the definition of the `Sequence` type (I took it out of the `List` definition intentionally). This is how `serde` works, we do not have control over that.

In that case you should mark field as `#[serde(default)]` or use `Option<Sequence>` as a type.

See also the tests: https://github.com/tafia/quick-xml/pull/387/files#diff-78461d026840e91b6b02137004e4a9c6b3dd22b710843079743c9d471b1d3c6bR1077-R1086
