### ISSUE TITLE
Maintainence status

### ISSUE THREAD

**Issue by dralley** [tafia/quick-xml#366]
@tafia 

First, I really have to thank you for all the work you've put into this library!  It's great, probably the best XML library there is for Rust.

Could you help set some expectations around how much availability you have for PR reviews and releases?  If there is something I (or others) could do to help, like contributing to PR reviews, then I'd be willing to do that.  But without guarantees that it will eventually be looked at, merged, released etc. it's hard to justify the time investment - and I also wouldn't want to mislead the contributor into thinking a review from me actually means that their PR is moving forwards.

And if you really have no availability (which is fine, I will never criticize anyone for not being able to spend hours of their free time on unpaid work), would you consider giving commit access to someone like @Mingun (if they're interested)?

**Comment by Mingun** [comment]
I would be happy to do some maintenance work, because actually I have some thoughts about improvements in the library (mostly in the `serde` integration part). But I need warn you that I have no real projects that using Rust at all, so my work would be fully enthusiastic. For now I have feelings that I can do it, but probably that will be not always ;)

**Comment by dralley** [comment]
I'm trying to convince people that we should use a library I wrote using quick-xml in production :)  So I would love to try to keep my dependencies healthy.  I'm just not much of an XML expert, generally speaking, beyond the small subset that I'm using - so I don't think I should necessarily be "that person" by myself.  Although there are plenty of small bugs that I would feel comfortable reviewing.

**Comment by dralley** [comment]
@tafia How do you feel about this?

**Comment by dralley** [comment]
Well, it's been 2 months, and I emailed him directly about 3 weeks ago, not sure what to do now.

**Comment by Mingun** [comment]
Did the same with the same result about 2 weeks ago. So I detach [my fork](https://github.com/Mingun/fast-xml) and publish it as [fast-xml](https://lib.rs/crates/fast-xml) crate. Anyone feel free to retarget their PRs to my fork (GitHub support should detach it soon then Issues will be available). I plan to made a 0.23 and 0.24 releases soon -- 0.23 with only obvious bug fixes that I found while working on my PRs and all other in 0.24.

**Comment by dralley** [comment]
Sounds good - I will copy over my PRs.  

For what it's worth, if @tafia does return, I would still prefer to reconcile the two and keep moving forwards under the original name if the maintainership situation can be resolved.

**Comment by tafia** [comment]
Hi guys,

Sorry for the late response, work got most of my time.

I'd be happy share ownership with people willing to maintain it as I don't see the situation improving as I was expecting and feel very bad for all of you, again very sorry. 

If interested, please send me an email on my non github address (as it is extremely noisy):
johann.tuffe@gmail.com

**Comment by Mingun** [comment]
Ok, I repeat my previous letter ;)
 
Hello there, 
 
I’m glad to hear, that’s you ok in that time where COVID19 exists. Because I already took the trouble to maintaining my own fork, I think, I could ask you to share ownership. My main goal is to polish serde support (deserializer mostly), but I’ve already dive too deep into the project when fixing bugs that I’ve found during my work on the project, so I think I also can finish proper support for namespacing and serializer part of serde and maintain project for some time at least. For now I have dozen active branches locally with various improvements, that I’ll plan to merge.
 
Also, for reference, there is my previous message to your GitHub address:
 
Hello there, 
 
Your crate  quick-xml the second most popular crate for working with XML according to the  crates.io and  libs.rs . Unfortunately, I see that you right now you have no time to maintain it and you have abandoned your GitHub account in general. (As a side node, the first crate by popularity,  xml-rs , also seems abandoned.) So, maybe you can give your project a second life, if you give maintenance rights to someone else, who can review and merge PRs and release new versions.
 
If you think it makes sense, then could you respond in  https://github.com/tafia/quick-xml/issues/366 ? Although I do not want to get involved with any maintenance work, nevertheless I will support the project if you decide to give me these rights (because anyway I need in an XML parser with correct serde integration and I already spend a some time to try make it work).
 
Cheers,
Mingun,  https://github.com/Mingun/
>Четверг, 19 мая 2022, 14:09 +05:00 от Johann Tuffe ***@***.***>:
> 
> 
>Hi guys,
>Sorry for the late response, work got most of my time.
>I'd be happy share ownership with people willing to maintain it as I don't see the situation improving as I was expecting and feel very bad for all of you, again very sorry.
>If interested, please send me an email on my non github address (as it is extremely noisy):
***@***.***

**Comment by dralley** [comment]
Given how little time has passed since the fork and the wide adoption of `quick-xml` I do think it would be better to continue with quick-xml.  

At the moment I don't have a lot of spare time to do coding on the side, but I would definitely help with getting PRs reviewed and merged.

**Comment by tafia** [comment]
Thank you both!
I have added you as collaborator to the github repo and added as a owner of the crate on crates.io side.
Let me know if it is working for you.
Thank you so much for helping the project staying alive!

**Comment by dralley** [comment]
Thanks @tafia !

I've made a PR to merge all the changes back upstream https://github.com/tafia/quick-xml/pull/385

**Comment by tafia** [comment]
Awesome!
