### ISSUE TITLE
test_writer_indent_cdata fails on linux with stray "13" items

### ISSUE THREAD

**Issue by decathorpe** [tafia/quick-xml#443]
Running the test suite for quick-xml 0.23.0 on Fedora Linux with stray "13" items.
It looks like this test discriminates between windows and not(windows) for some reason:
https://github.com/tafia/quick-xml/blob/master/tests/unit_tests.rs#L264

And it seems that the reason to discriminate between windows and not(windows) might no longer be there?

Environment: Fedora Linux 36 on x86_64 with Rust 1.62.0

```
thread 'test_writer_indent_cdata' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
 [
     60,
     63,
     120,
     109,
     108,
     32,
     118,
     101,
     114,
     115,
     105,
     111,
     110,
     61,
     34,
     49,
     46,
     48,
     34,
     63,
     62,
>    13,
     10,
     60,
     106,
     111,
     98,
     115,
     62,
>    13,
     10,
     32,
     32,
     32,
     32,
     60,
     106,
     111,
     98,
     62,
>    13,
     10,
     32,
     32,
     32,
     32,
     32,
     32,
     32,
     32,
     60,
     106,
     111,
     98,
     105,
     100,
     62,
     60,
     33,
     91,
     67,
     68,
     65,
     84,
     65,
     91,
     48,
     48,
     100,
     52,
     54,
     101,
     52,
     52,
     57,
     52,
     101,
     49,
     93,
     93,
     62,
     60,
     47,
     106,
     111,
     98,
     105,
     100,
     62,
>    13,
     10,
     32,
     32,
     32,
     32,
     60,
     47,
     106,
     111,
     98,
     62,
>    13,
     10,
     60,
     47,
     106,
     111,
     98,
     115,
     62,
 ]
```

**Comment by dralley** [comment]
There's a lot of reasons I'm going to be very happy about the API redesign, and one of them is not having to look at lists of digits.

>And it seems that the reason to discriminate between windows and not(windows) might no longer be there?

It's definitely possible.  Will try to take a look later

**Comment by Mingun** [comment]
It seems that it is depend on the way of how git's checkout test XML files (EOL mode)

**Comment by decathorpe** [comment]
That sounds like it's safe to ignore this specific test failure?

**Comment by Mingun** [comment]
I would like to change the git rules to treat all files in `test/documents` directory as binary and remove from tests any platform-specific code

**Comment by Mingun** [comment]
Strange, but repository already contains `.gitattributes` file, but on my windows machine line endings of XML files still converted to CRLF...
https://github.com/tafia/quick-xml/blob/c1455760cbca7f6e1d46c73f537dfb9c3df365ba/.gitattributes#L1-L2

**Comment by Mingun** [comment]
I found that
- repository contains `/tests/documents/*` files with LF endings. Checked that by checkout on linux where `core.autocrlf=false`
- checkout on linux uses LF ending in working copy
- checkout on Windows uses CRLF ending in working copy, because of my local `git config core.autocrlf=true`, which is normally fine for files with the code
- `*.xml text eol=cr` does nothing, according to [this answer](https://stackoverflow.com/a/20653073/7518605). I suspect that `*.xml text eol=lf` should be used
- `*.xml text eol=lf` does not change situation on Windows immediately, you should run `git add --renormalize .` to tell git that LF -> CRLF change due to `git config core.autocrlf=true` in your working copy is an actual change now and then `git reset --hard` to remove that changes
- on Windows `utf16le.xml`, `utf16be.xml` and `sample_5_utf16bom.xml` may be broken on checkout because of incorrect LF -> CRLF conversion, which inserts bytes assuming UTF-8 input. As a result, file content was changed:
![sample_5_utf16bom.xml before fixing .gitattriubtes](https://user-images.githubusercontent.com/450131/183483064-0c176d2e-07c1-40e2-b5e3-2b40ee41ca41.png)

@decathorpe, actually, it is strange, that test is failed on Linux. I would assume that you have `git config core.autocrlf=true` and your working copy have CRLF endings, which is unusual for Linux. Because our CI works on Ubuntu, I assume that your problem due to that reason and #454 should fix it. Could you check?

**Comment by decathorpe** [comment]
I did not run the tests from a git checkout, but from the canonical sources that are uploaded to crates.io. So the contents of those files might depend on which system "cargo publish" was run on.

**Comment by Mingun** [comment]
Yes, 0.23.0 I've built on Windows. So it seems a good theory
