### ISSUE TITLE
no method named `read_text` found for struct `Reader<BufReader<File>>

### ISSUE THREAD

**Issue by sergeken** [tafia/quick-xml#470]
After upgrading to 0.24 the function reader.read_text() is not implemented for BufReader<File>

**Comment by dralley** [comment]
That's intentional, you should use `reader.read_text_into(...)`.  `reader.read_text()` is now equivalent to what `reader.read_text_unbuffered()` was, and it is only available when working with slices.

**Comment by Mingun** [comment]
Yes, it was removed, because it returns unexpected results in some cases. It was trivially implemented and now you should manually match `Event::Text` to get similar results. New [`read_text()`](https://docs.rs/quick-xml/latest/quick_xml/reader/struct.Reader.html#method.read_text) does slightly different thing, that is more useful. It is not trivial to implement it for buffered reader, because we do not buffer markup bytes and spaces, that will not returned as parts of events

**Comment by sergeken** [comment]
Thank you.
It wasn't obvious from the documentation.
