### ISSUE TITLE
quick-xml requires implicitly enabled `serde/derive`

### ISSUE THREAD

**Issue by loyd** [tafia/quick-xml#473]
It's impossible to depend on `quick-xml/serialize` without depending on `serde/derive`

Details: #472

**Comment by Mingun** [comment]
@loyd , could you please describe, how you face with this problem? You tried to use quick-xml in a crate with `resolver="2"` field?

**Comment by loyd** [comment]
I've fixed [`fixnum`](https://github.com/loyd/fixnum) to support `<tag>42.42</tag>` parsing (by implementing `visit_map`). `fixnum` doesn't use `serde/derive`.

So, now it's fixed by enabling [`serde/derive`](https://github.com/loyd/fixnum/blob/ad0ba674caf30862d6183b9e4ae2d01c31cac159/Cargo.toml#L42).

But it also requires [`serde/derive` in dev-dependencies](https://github.com/loyd/fixnum/blob/ad0ba674caf30862d6183b9e4ae2d01c31cac159/Cargo.toml#L62), but it's inconvenient and allows to fail in the future (because not all feature combinations are checked by `clippy`, a lot of them).

**Comment by Mingun** [comment]
I've almost done with rewriting 
> Btw, [`next_key()`](https://github.com/loyd/fixnum/blob/ad0ba674caf30862d6183b9e4ae2d01c31cac159/src/serde.rs#L128) cannot parse into `&str` (and `next_value()` too until v0.24 version). But it's a subject of another issue.

Yes, that is [known problem](https://github.com/tafia/quick-xml/issues/328)

> I've fixed [`fixnum`](https://github.com/loyd/fixnum) to support `<tag>42.42</tag>` parsing (by implementing `visit_map`).

The problem with map is that deserialization performed using `deserialize_any`. It have many drawbacks for non-self-describing deserializers and deserializers with weak type systems. XML has only two types: string and map, and `<tag>42.42</tag>` is mapped to `map!["$value" -> "42.42"]`. Probably it would be better to request `deserialize_u128` or deserialize into untagged enum (which is under hood is sequence of `if let Ok(x) = deserialize_x() { x } else if let Ok(y) = deserialize_y() { y } else ...`):
```rust
#[derive(Deserialize)]
#[serde(untagged)]
enum Value {
  U8(u8),
  I8(i8),
  ...
  U128(u128),
  I128(i128),
  String(String),
}
```
and then convert in into `FixedPoint`.

This would be especially useful because I plan to rename `$value` key to `#text` (actually split it into `#text` and `#content` as described in https://github.com/tafia/quick-xml/issues/383#issuecomment-1120244201), which of course break your code.

**Comment by Mingun** [comment]
@loyd, can you please post exact instruction, what I should do to reproduce that? I didn't see a `resolver="2"` field in the [fixnum Cargo.toml](https://github.com/loyd/fixnum/blob/ad0ba674caf30862d6183b9e4ae2d01c31cac159/Cargo.toml)

**Comment by loyd** [comment]
> The problem with map is that deserialization performed using deserialize_any. It have many drawbacks for non-self-describing deserializers and deserializers with weak type systems. 

Yep, a previous version uses `deserialize_str` for human-readable formats. But I need to support both parsing from `str` and from `f64`, so I've changed to `deserialize_any`.

> Unfortunately, your code will break in one of next quick-xml release, because I plan to rename $value key to #text

It's ok, just specify it in the changelog explicitly.

> @loyd, can you please post exact instruction, what I should do to reproduce that? I didn't see a resolver="2" field in the [fixnum Cargo.toml](https://github.com/loyd/fixnum/blob/ad0ba674caf30862d6183b9e4ae2d01c31cac159/Cargo.toml)

`resolver="2"` is for facing the problem in `quick-xml`. So, steps (in `quick-xml` repo):
* Add `resolver = "2"` to `quick-xml` (or `edition = "2021").
* Run `cargo clippy --features serde`

It works fine with v1 because there is `serde/derive` dev-dep

**Comment by xkr47** [comment]
I can reproduce this issue with these commands in an empty directory:
```sh
cargo init
echo 'quick-xml = { version = "0.26.0", features = [ "serialize" ] }' >> Cargo.toml
cargo build
```
By additionally issuing the below command, `cargo build` succeeds.
```sh
echo 'serde = { version = "1.0", features = [ "serde_derive" ] }' >> Cargo.toml
```
