### ISSUE TITLE
Can't postpone deserializing of inner data

### ISSUE THREAD

**Issue by sven** [tafia/quick-xml#515]
Hi,

I'm trying to use the flatten attribute so I can only deserialize the outer struct. The deserializing of the inner struct should be done later by another function.

So far I tried this which doesn't compile:

```rust
use quick_xml::de::from_str;
use serde::Deserialize;
use std::collections::HashMap;

#[derive(Debug, Deserialize)]
#[serde(rename = "one")]
pub struct One {
    pub two: Two,
}

#[derive(Debug, Deserialize)]
pub struct Two {
    #[serde(flatten)]
    pub three: HashMap<String, String>,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let xml = "<one><two><three><four></four></three></two></one>";
    let data: One = from_str(xml)?;
    println!("{:#?}", data);

    Ok(())
```

When using the serde_yaml crate it has the element `Value` which can be used for this like:

```rust
pub three: serde_yaml::Value
```

Is there a way with quick_xml to only parse until a given element is reached and let it eat all the inner data into a string (or special object) which can than be forwarded to another function and continue parsing with their logic?

Thank you!
  Sven

**Comment by Mingun** [comment]
quick_xml does not have a type similar to `serde_yaml::Value` and probably never will have, because XML very poorly interacts with [`deserialize_any`](https://docs.rs/serde/latest/serde/trait.Deserializer.html#tymethod.deserialize_any). XML is not self-describing format unlike YAML (that means that you cannot distinguish between strings and numbers, for example). serde has not enough flexibility to fully support XML.

You still can use `serde_yaml::Value`, `serde_json::Value` or [`serde_value::Value`](https://docs.rs/serde-value/latest/serde_value/enum.Value.html), but in a very limited way. For example, you will never get a [`Seq`](https://docs.rs/serde-value/latest/serde_value/enum.Value.html#variant.Seq) variant, because in XML sequences has no explicit form.

Of course, you still can try to implement such `quick_xml::Value` by yourself and propose a PR, but I doubt that it will be possible to solve its numerous problems.

**Comment by JOSEPHGILBY** [comment]
@Mingun could this be a duplicate of #257? If they had 

```rust
use quick_xml::de::from_str;
use serde::Deserialize;
use std::collections::HashMap;

#[derive(Debug, Deserialize)]
#[serde(rename = "one")]
pub struct One {
    pub two: Two,
}

#[derive(Debug, Deserialize)]
pub struct Two {
    #[serde(rename = "$text")]
    pub three: String,
}
```
with a fix for the issue, wouldn't the field three then contain `<three><four></four></three>` and @sven could later run that string through a separate deserialization?

**Comment by sven** [comment]
Thanks for your discussion. For now I was able to work around this by using another interface to get the needed data but it sounds like this could be made possible in the future.
