### ISSUE TITLE
Deserializing data into an untagged enum with serde

### ISSUE THREAD

**Issue by seanpianka** [tafia/quick-xml#525]
# Problem description

Hello 👋 I've been setting up the data models/types to automatically deserialize XML data from an API into a set of types, but I'm struggling with a particular issue involving untagged enums.

The XML data I'm receiving can include data of two formats, and I would like to deserialize the XML data into whichever type it can successfully deserialize into first.

# Example XML data

Format 1: text containing a reference/href
```xml
       <ServiceLocation xmlns="http://naesb.org/espi/customer">
            <UsagePoints>
                <UsagePoint>https://api.com/DataCustodian/espi/1_1/resource/Subscription/1/UsagePoint/100</UsagePoint>
                <UsagePoint>https://api.com/DataCustodian/espi/1_1/resource/Subscription/1/UsagePoint/200</UsagePoint>
            </UsagePoints>
        </ServiceLocation>
```

Format 2: fully-expanded
```xml
       <ServiceLocation xmlns="http://naesb.org/espi/customer">
            <UsagePoints>
                <UsagePoint>
                  <serialNumber>100</serialNumber>
                  <status>On</status>
                </UsagePoint>
                <UsagePoint>
                  <serialNumber>200</serialNumber>
                  <status>On</status>
                </UsagePoint>
            </UsagePoints>
        </ServiceLocation>
```

# Solution attempt

I want to deserialize this data into a single type, where a field containing an enum can contain either of these variants. 

## Type definitions
Here's my attempt at a type definition:

```rust
#[derive(Debug, serde::Deserialize)]
struct ServiceLocation {
    #[serde(rename = "UsagePoints")]
    usage_points: Option<Vec<UsagePoint>>
}

#[derive(Debug, serde::Deserialize)]
#[serde(untagged)
enum UsagePoint {
    UsagePointReference(UsagePointReference),
    UsagePointFull(UsagePointFull)
}

#[derive(Debug, Deserialize)]
struct UsagePointReference {
    #[serde(rename = "#text")]
    href: Url,
}

#[derive(Debug, Deserialize)]
struct UsagePointFull {
    #[serde(rename = "serialNumber")]
    serial_number: String,
    status: String
}
```

## Deserialization error
Here's the error I received when providing either of the XML blobs (shown in the previous section) to a call of `quick_xml::de::from_str`:

```rust
called `Result::unwrap()` on an `Err` value: Custom("data did not match any variant of untagged enum UsagePoint")
thread 'resources::customer::tests::should_parse_service_location_with_usagepoint_reference' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("data did not match any variant of untagged enum UsagePoint")', 
```

If you could advise me on how I'm supposed to define the types to handle this variable situation regarding my data, or point me to docs where some similar use-case is elaborated on, I'd really appreciate it. 

Thanks!

**Comment by Mingun** [comment]
Correct deserialization of enums is not implemented yet, in some cases that is just impossible due to serde bugs. See [this set of tests](https://github.com/tafia/quick-xml/blob/e877f4fe2f5c9ea920bca25aedccb332cbad2f02/tests/serde-de.rs#L5746) to see what is possible and what is not.

Using `$text` with enums does not yet checked. There are still no consistent vision of how such enums should be mapped to XML. If you would to help, I suggest make an investigation by creating set of tests like the mentioned above.

**Comment by Mingun** [comment]
I also note, that you use `#text` instead of `$text`. `#text` was the initial proposal, but was leave as `$text` in order to not broke existing crates and kept compatibility with `xml-rs` at least in some cases.

The `ServiceLocation` should be defined slightly differently. You cannot skip definition of a struct for `UsagePoints` container. The correct definition should be:
```rust
#[derive(Debug, serde::Deserialize)]
struct ServiceLocation {
    #[serde(rename = "UsagePoints")]
    usage_points: UsagePoints,
}
#[derive(Debug, serde::Deserialize)]
struct UsagePoints {
    #[serde(rename = "UsagePoint", default)] # default to not fail on empty vectors
    usage_point: Vec<UsagePoint>,
}
```

**Comment by seanpianka** [comment]
Thank you for the code example/revision. I'll use this and see if I can continue to make progress.

**Comment by Mingun** [comment]
Unfortunately, you cannot deserialize untagged enums due to limitations of serde. `#[serde(untagged)]` requires self-describing format, and XML is not a such format.

In particular, you case is defined here:
https://github.com/tafia/quick-xml/blob/967d60dffdf23aa9c34c7d85ec3575a4cadc45cb/tests/serde-de.rs#L5836-L5851
As you can see, tests are ignored due to https://github.com/serde-rs/serde/issues/1183.

Because we cannot fix this from quick-xml side, I'll close this issue.
