### ISSUE TITLE
[Question]: Can't deserialize in HashMap<String, String> if there is a subelement

### ISSUE THREAD

**Issue by Arthur-PI** [tafia/quick-xml#526]
# Problem Description
Hello, I want to deserialize a list of unknown elements, that contains either a String literal or a sub element, but in case of a sub element I just want a default empty String. And I want to store this in an HashMap<String, String>

# What I've found so far
Let say I have this XML
```xml
<Data>
    <A>value1</A>
    <B>value2</B>
    <C>value3</C>
    <D>
        <Nested>Breaks !</Nested>
    </D>
</Data>
```
Where A, B, C have unknown name and their values are strings. I have this code struct that deserialize just well if I have only A, B and C.
```rs
#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
struct Event {
    #serde[(default)]
    data: HashMap<String, String>,
};
```
Here, if all my sub elements A, B and C contains only strings it works just well, but if I have a nested element in one of them like in D I have a `UnexpextedStart([78,101,115,116,101,100])` error (the int array represent the ascii codes for 'Nested').
So my question is, is there a way to either skip D if there is a nested element that is not a String, or define a default value like "" in those case to not lose all the rest of the data.
Thank you for your time 😄

**Comment by Mingun** [comment]
You should use a custom type that would be able to be deserialized using either [`Visitor::visit_str`](https://docs.rs/serde/latest/serde/de/trait.Visitor.html#method.visit_str) or [`Visitor::visit_map`](https://docs.rs/serde/latest/serde/de/trait.Visitor.html#method.visit_map). The `String::deserialize` only expect `Visitor::visit_str`. It seems that untagged enum
```rust
#[derive(Deserialize)]
#[serde(untagged)]
enum MyString {
  Str(String),
  Nested,
}
```
should do the work, but probably manually implemented `Deserialize` will be more ergonomic.

Because this issue is duplicate of #383, I close it.

**Comment by treywelsh** [comment]
Hi, 

It seems I have a similar problem, I want to capture keys and values in a HashMap (the difference is that I'm using HashMap temporarily, for the time of the deserialization) and I'm interested in the solution for this issue.
I already asked my question on stack overflow https://stackoverflow.com/questions/75337112/deserializing-dynamic-xml-in-rust

I didn't find a way to make this work via untagged enum (I wasn't able to capture key **and** values) so I took the "Implement Deserialize for a custom map type" serde example to update it a bit:
```
#![allow(dead_code)]

use serde::Deserialize;
use std::{collections::HashMap, fmt};

use serde::de::{self, Deserializer, MapAccess, Visitor};

const XML: &str = r#"
<vm>
    <id>15</id>
    <template>
        <tag1>content1</tag1>
        <tag2>content2</tag2>
        <vec1>
            <tag3>content3</tag3>
            <tag4>content4</tag4>
        </vec1>
        <vec1>
            <tag3>content5</tag3>
        </vec1>
        <tag2>content6</tag2>
        <vec2>
            <tag3>content7</tag3>
        </vec2>
    </template>
</vm>
"#;

#[derive(Debug, Clone)]
struct Pair(String, String);

#[derive(Debug, Clone)]

struct Vector(String, Vec<Pair>);

#[derive(Debug, Clone)]
struct Template {
    pairs: Vec<Pair>,
    vectors: Vec<Vector>,
}

impl Template {
    fn new() -> Self {
        Template {
            pairs: Vec::new(),
            vectors: Vec::new(),
        }
    }
}

#[derive(Debug, Deserialize)]
pub struct VM {
    id: i64,
    template: Template,
}

struct TemplateVisitor;

impl<'de> Visitor<'de> for TemplateVisitor {
    type Value = Template;

    fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
        formatter.write_str("a very special map")
    }

    fn visit_map<M>(self, mut access: M) -> Result<Self::Value, M::Error>
    where
        M: MapAccess<'de>,
    {
        let mut map = Template::new();

        while let Some(key) = access.next_key::<String>()? {
            let map_value = access.next_value::<HashMap<String, String>>().unwrap();

            if map_value.contains_key("$text") {
                map.pairs
                    .push(Pair(key, map_value.get("$text").unwrap().clone()));
            } else {

                let mut vector = Vec::new();
                for (k, v) in map_value {
                    vector.push(Pair(k, v))
                }
                map.vectors.push(Vector(key, vector));
            }
        }

        Ok(map)
    }
}

impl<'de> Deserialize<'de> for Template {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        deserializer.deserialize_map(TemplateVisitor {})
    }
}

fn main() {
    let obj: VM = serde_xml_rs::from_str(XML).unwrap();
    println!("{:#?}", obj);
}
```

Did you find an other interesting solution @Arthur-PI ?
I'm not happy with the test `map_value.contains_key("$text")`, I'm feeling like I'm doing something dirty. Any tip to share @Mingun ? 

Sorry if this comment was not appropriate in this issue, I wasn't sure that #383 was really a duplicate of this one ?

**Comment by Mingun** [comment]
I do not see abilities to avoid `map_value.contains_key("$text")` hack. What's happens there:
```rust
// `key` deserialized from
// - <tag1>
// - <tag2>
// - <vec1>
// - <vec1>
// - <tag2>
// - <vec2>
while let Some(key) = access.next_key::<String>()? {
    // map_values deserialized from ... to
    // - <tag1> content1 </tag1>
    //          ^^^^^^^^              -- map: { $text: content1 }
    // - <tag2> content2 </tag2>
    //          ^^^^^^^^              -- map: { $text: content2 }
    // - <vec1> <tag3>content3</tag3><tag4>content4</tag4> </vec1>
    //          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ -- map: { tag3: content3, tag4: content4 }
    // - <vec1> <tag3>content5</tag3> </vec1>
    //          ^^^^^^^^^^^^^^^^^^^^^ -- map: { tag: content5 }
    // - <tag2> content6 </tag2>
    //          ^^^^^^^^              -- map: { $text: content6 }
    // - <vec2> <tag3>content7</tag3> </vec2>
    //          ^^^^^^^^^^^^^^^^^^^^^ -- map: { tag3: content7 }
    let map_value = access.next_value::<HashMap<String, String>>().unwrap();

    if map_value.contains_key("$text") {
        map.pairs
            .push(Pair(key, map_value.get("$text").unwrap().clone()));
    } else {

        let mut vector = Vec::new();
        for (k, v) in map_value {
            vector.push(Pair(k, v))
        }
        map.vectors.push(Vector(key, vector));
    }
}
```
PS. I would better to use [HashMap::remove](https://doc.rust-lang.org/stable/std/collections/hash_map/struct.HashMap.html#method.remove) instead of `contains_key` + `get`.

https://serde.rs/string-or-struct.html example does not work here, because both [`deserialize_str`](https://docs.rs/serde/latest/serde/trait.Deserializer.html#tymethod.deserialize_str) and [`deserialize_map`](https://docs.rs/serde/latest/serde/trait.Deserializer.html#tymethod.deserialize_map) can handle `content1` and `<tag3>content5</tag3>` and return
- `String(content1)` and `String(content5)`
- `HashMap{ $text: content1 }` and `HashMap{ tag: content5 }`

so enum couldn't distinguish between them (it relies on deserialization failure). Moreover, because deserializer is consumed during deserialization, ([`Deserialize::deserialize`](https://docs.rs/serde/latest/serde/trait.Deserialize.html#tymethod.deserialize) takes ownership) the deserialization is performed into an internal [`serde::de::__private::Content`](https://github.com/serde-rs/serde/blob/692ac99c694714d3c5f0d34902ed1c7622a0e60a/serde/src/private/de.rs#L220) type, which uses [`deserialize_any`](https://docs.rs/serde/latest/serde/trait.Deserializer.html#tymethod.deserialize_any).

Probably, if we'll change our `deserialize_any` implementation, we could solve your case by using untagged enum
```rust
#[derive(Deserialize)]
#[serde(untagged)]
enum {
  String(String),
  Map(HashMap<String, String>),
}
```
https://github.com/tafia/quick-xml/blob/64292c73794ff7abb6b5883250b6631a2e92667a/src/de/mod.rs#L2525-L2536
The `self.peek()` here peeks a `<tag1>`, `<tag2>` and so on.

Feel free to investigate this! That could open a rabbit hole!

**Comment by treywelsh** [comment]
Thanks for taking time to answer !

**Comment by codingbaobao** [comment]
Hi, I have a similar question to transform into hashmap
```
<imgdir name="info">
    <int name="version" value="10" />
    <float name="speed" value="1.6" />
    <string name="path" value="a/b/c" />
</imgdir>
```
I have an Enum to handle different types
```
enum Value {
    Int(i32),
    Float(f32),
    String(String),
}
```
And I want to transform this xml into HashMap<@name,@value>
```
#[derive(Debug, Clone)]
struct MyMap(HashMap<String, Value>);

struct Imgdir {
    #[serde(rename = "@name")]
    name: String,
    #[serde(rename = "$value")]
    map: HashMap<String, Value>,
}
```
I implement `Visitor` trait like @treywelsh did,  however seems like it gets error on `access.next_value::<HashMap<String, String>>()`.
Could you give some tips to get it right? Or it just can't :( @Mingun
