### ISSUE TITLE
Deserialization doesn't process @ for attributes correctly

### ISSUE THREAD

**Issue by rrichardson** [tafia/quick-xml#553]
In order to include it as an attribute in an element, I used `#[serde(rename = "@xsi:type")]` which causes it to serialize correctly,  e.g. `<MyElement xsi:type="MyType">` 

However, deserialization of the same blob fails because 

```
"missing field `@xsi:type`"
```

Repro: 

```rust
  #[derive(Clone, Debug, Default)]
  #[derive(serde::Serialize, serde::Deserialize)]
  pub struct Grantee {
      #[serde(rename = "ID")]
      #[serde(skip_serializing_if = "Option::is_none")]
      pub id: Option<ID>,
      #[serde(rename = "@xsi:type")]
      pub r#type: TypeEnum,
      #[serde(rename="@xmlns:xsi")]
      pub ns_import: Option<String>
  }
  ```
  
  Serialization produces XML which seems correct: 
  ```xml 
 <Grantee xsi:type="Group" xmlns:xsi="http://s3.amazonaws.com/doc/2006-03-01/">
     <ID>N0NX8</ID>
 </Grantee>
 ```
 
But deserialization produces the above result.

**Comment by Mingun** [comment]
Deserialization of XML Namespace bindings (`xmlns:xsi` in your case) was fixed in #539.
Deserialization of namespaced items ignores the namespace prefix, so you should rename the field to `type`, but then it will be serialized as `type` instead of `xsi:type`. As a workaround you could try to use
```rust
      #[serde(rename = "@xsi:type")]
      #[serde(alias = "@type")]
      pub r#type: TypeEnum,
```
Then the field will be serialized as `xsi:type` attribute and deserialized from `type`, `<any-prefix>:type` or `<any-prefix>:xsi:type` attributes.

**Comment by rrichardson** [comment]
This solved my problem.  I'm assuming that this is the final intended design, so I'll close this ticket.  Feel free to re-open if you want to support this in a different way.

**Comment by BenjaminBrienen** [comment]
> ```rust
>       #[serde(rename = "@xsi:type")]
>       #[serde(alias = "@type")]
> ```

Can this please go into the documentation somewhere? After 3 crates and hours of digging, I finally find a "workaround".
