### ISSUE TITLE
`read_event` vs. `read_namespaced_event`

### ISSUE THREAD

**Issue by pfernie** [tafia/quick-xml#59]
Interleaving calls to `read_event` and `read_namespaced_event` could lead to surprising behavior (internal stack of namespaces would not be properly maintained?). It seems the `Reader` should always be either tracking or not tracking the namespaces, and as such should expose some configuration `fn parse_namespaces(self, parse: bool) -> Self`. That, or perhaps there should be separate implementations, `EventReader`, `NamespacedEventReader`, with only the latter exposing fns such as `read_namespaced_event`.

**Comment by pfernie** [comment]
I added a [gist](https://gist.github.com/pfernie/c2b1176fc57fa902ed11351a16e89a70) showing an (admittedly pathological) usage of `read_event` & `read_namespaced_event` to illustrate.

**Comment by Mingun** [comment]
Yes, the current design of reading namespaces are not good. I'd prefer that namespace buffer would be in the `Reader`, because, unlike buffer for events, I cannot imagine why the user may want to clear it -- if he/she would do that, he/she lose all namespaces information and probably even breaks quick-xml.

PR for moving namespaces buffer inside `Reader` and always be aware of namespaces is welcome.

**Comment by dralley** [comment]
@Mingun Is there any work left here or can it be closed?

**Comment by Mingun** [comment]
Done in #437, can be closed
