### ISSUE TITLE
Invalid close tag is parsed successfully

### ISSUE THREAD

**Issue by Aaron1011** [tafia/quick-xml#622]
Parsing the string "><" produces `Event::Text(BytesText { content: Borrowed(">") })` followed by `Event::Eof`. However, this is an invalid XML string, and should result in some kind of error (or detectable error condition).

Reproduction:

```rust
use quick_xml::Reader;
use quick_xml::events::Event;

fn main() {
    
    let mut reader = Reader::from_str("><");
    reader.trim_text(true);
    
    loop {
        let event = reader.read_event().expect("Failed to read event");
        eprintln!("Event: {event:?}");
        if let Event::Eof = event {
            break;
        }
    }
}
```

outputs:

```
Event: Text(BytesText { content: Borrowed(">") })
Event: Eof
```

**Comment by Mingun** [comment]
To be clear: error here is only in emitting `Event::Eof` instead raising error about incomplete markup. `>` in the beginning correctly recognized as a text, because the only symbols that MUST be escaped in text in XML is `<` and `&` (see definition of [`CharData`](https://www.w3.org/TR/xml11/#dt-chardata))
