### ISSUE TITLE
schema generator

### ISSUE THREAD

**Issue by Thomblin** [tafia/quick-xml#694]
Hi there,

I started a small project a while ago to parse an xml file and generate the structs that one needs to parse that xml with serde / quick_xml_de. If you think this could be helpful I would love to discuss how we could relate both projects and which further improvements would be helpful. You can find the project at https://github.com/thomblin/xml_schema_generator

Best,
Sebastian

**Comment by Mingun** [comment]
I looked at your project -- you tries to guess the schema from one instance of XML of that schema. In my opinion, such programs has very limited use-cases, because their result are often too probabilistic. For example, they will not be able to detect a sequence if only one element is present in instance. But may be useful for somebody.

We can, however, mention your project in readme or at [de](https://docs.rs/quick-xml/latest/quick_xml/de/index.html) page if you send a PR.

I also would like to head a feedback from you as a user of the library. If you find some things unergonomic or too complicated, feel free to share your experience, as well as thoughts how we can improve them.

**Comment by Thomblin** [comment]
Thanks a lot for your input. I assume that you want to parse multiple XML files to receive a better matching struct as a result: Actually that was on my list of ideas and I was able to implement that with minimal effort (new function extend_struct beside the existing into_struct). If you have a certain use case (XML files) at hand then I would like to give it a try with a more sophisticated example, it works well with my small test cases.

As you ask for feedback regarding using quick_xml. I think in general it is obvious how to build structs that match an XML file even if that might take some time. In my current use case I implement several endpoints that usually return XML with a stable structure. Thus one XML example was good enough for me to create a compatible struct or at least something that needs minimal adaption to work with further XML files. However I needed to parse an 80MB XML file and creating a valid structure for such a file manually appears to be a lot of works, especially as I struggled a lot to understand and trace back error messages if parsing the XML into a struct went wrong. That's why I started this project (and as a learning experience). Additionally I guess the automation to create (at least the backbone of the resulting) struct might save everyone some time.

Thanks for your invite to at least leave a comment in the readme or the de page, I am happy to add that later.

If you have other thoughts how I could improve the library to be useful for maybe use cases that you have in mind, I would be happy to hear them.
