### ISSUE TITLE
Enum Variants with Repeated Fields

### ISSUE THREAD

**Issue by spiegela** [tafia/quick-xml#710]
I'm encountering an error when using repeated fields within enum variant type. Here's a test case that reproduces the error:

```rust
    #[test]
    fn test_enum_variant_with_repeated() {
        #[derive(Debug, Deserialize)]
        #[serde(tag = "@type", rename_all = "lowercase")]
        enum Kind {
            One(OneType),
            Two(()),
        }
        #[derive(Debug, Deserialize)]
        struct OneType {
            #[serde(default)]
            item: Vec<()>
        }
        let value = r#"<kind type="one"> <item/> <item/> </kind>"#;
        let el: Kind = quick_xml::de::from_str(value).unwrap();
        if let Kind::One(o) = el {
            assert_eq!(o.item.len(), 2);
        } else {
            panic!("wrong item type");
        }
    }
```

This case returns this error, which indicates the deserializer is expecting a `map`/`struct` instead of a `Vec<>`.
```
called `Result::unwrap()` on an `Err` value: Custom("invalid type: map, expected a sequence")
thread 'mvce::tests::test_enum_variant_with_repeated' panicked at src/mvce.rs:140:55:
called `Result::unwrap()` on an `Err` value: Custom("invalid type: map, expected a sequence")
```

**Comment by Mingun** [comment]
Unfortunately, this cannot be fixed from quick-xml side, because of internal buffering that serde performs to find a tag in the data. In general, this is instance of serde-rs/serde#1183. In that case it could work if serde-rs/serde#1495 will be implemented, because this optimization will use original deserializer if the tag is the first field in data as here.
