### ISSUE TITLE
Parsing malformed closing tags

### ISSUE THREAD

**Issue by evilpie** [tafia/quick-xml#776]
For [Ruffle](https://ruffle.rs/) it would be useful if we could parse these two kinds of malformed XML:
```xml
<a></a/>
```
From https://github.com/ruffle-rs/ruffle/issues/15674. Note the extra `/`.
```xml
<a></a hello="world">
```
From https://github.com/ruffle-rs/ruffle/issues/16862. Note the attribute in the closing tag!

Excuse me if I missed a config option for this.

**Comment by Mingun** [comment]
I think, that should be possible today, because we do not check (yet. I plan to add optional `validate` method to events) content of the start / end events.

**Comment by dralley** [comment]
It's literally possible to construct such an event, however there's no way to get the attributes from it unless you parse them yourself.  `BytesEnd` doesn't provide any mechanism for this.

Looking at the documentation for `BytesEnd`: https://docs.rs/quick-xml/latest/quick_xml/events/struct.BytesEnd.html

We do give an example of creating such an event (although I think this isn't a great idea because it is currently our sole example - we should not have the sole example be a case of malformed XML).

But in this example the entire string, including the attributes, is returned when you call `.name()`.  I'm guessing that probably is not what you want @evilpie ?

**Comment by evilpie** [comment]
We don't actually care about the attributes or anything else in the closing tag. I just found about the config option `check_end_names`. Setting this to `false` almost gives us the Flash behavior.

However Flash treats `<a></a foo="bar">` and `<a></a/>` as just `<a></a>`, but it will throw for `<a></b>`, because the tags don't match ... The config option also allows the last one unlike Flash, so we can't use it directly.

**Comment by Mingun** [comment]
I know only one example which we do not support right now:
```xml
</a foo=">">
```
will be parsed as
```rust
Event::End(BytesEnd::new("/a foo=\""));
Event::Text(BytesText::from_escaped("\">"));
```

**Comment by evilpie** [comment]
Oh no. It does parse it ...
```
var xml = new XML('<a></a foo=">">')
trace(xml.toXMLString()) // <a/>
```

It does seem very unlikely to happen, so if that specific case would be very hard we might be able to skip it.

**Comment by Mingun** [comment]
No, that is simple to support. I think, we even may always parse this in such way, because anyway the tag name cannot contain neither `"` or `'` and any compliant parser will throw an error anyway. I plan to add an optional validate abilities which will reject such XMLs in any case no matter as we would parse it without validation.

**Comment by Mingun** [comment]
With release 0.36.0 it is possible to parse such XMLs without surprises.
