### ISSUE TITLE
modified Tag Attribute & Text

### ISSUE THREAD

**Issue by danielitzahi** [tafia/quick-xml#779]
hi
how can i only update the "Reader" data (Tag Attribute & Text)
do i need "Writer" for this ?
example:
```xml
<this_tag k1="v1" k2="v2"><child>text</child></this_tag>
```
update k2 to "v6"
child text to "foo"
tzahi

**Comment by Mingun** [comment]
What you mean under "update"? Do you want to get event from `Reader` and change its content? You cannot change existing event, but you can create a new one. Then you can use that event as if it was read by `Reader` (its lifetime will be different although). You need `Writer` only if you want to write updated XML to somewhere.

**Comment by danielitzahi** [comment]
Yes update data inside tag
So
It is possible to load xml with Writer
And update data by the event?
Thanks for your fast response (:
Tzahi

**Comment by Mingun** [comment]
The [Readme](https://github.com/tafia/quick-xml?tab=readme-ov-file#writer) actually gives you example of updating. In the example we read XML, get events and replace a start tag with name `this_tag`:
- we are create new tag with new name
- we are copy all attributes from readers' event. Here you can filter attributes which you copy and skip some of them
- we are add new attribute. If you'll add attribute with the same name as skipped on step two but with different value, you effectively update it
- we are write new tag instead of original

In the end we get updated document.
