### ISSUE TITLE
The `form_str` function is counterintuitive

### ISSUE THREAD

**Issue by lethargy123** [tafia/quick-xml#794]
I attempted to use the `form_str` function in version 0.36.1 and found it to behave quite counterintuitively. Figure 1 shows the code I initially tried, which resulted in an error. Figure 2 illustrates the conclusion I arrived at after extensive testing. I find the approach shown in Figure 2 to be rather complex. It's worth noting that the code in Figure 1 worked correctly in version 0.26 of quick-xml. The XML text being processed is as follows:
<data>
  <program SECTOR_SIZE_IN_BYTES="4096" file_sector_offset="0" filename="gpt_backup0.bin" label="BackupGPT" num_partition_sectors="5" partofsingleimage="true" physical_partition_number="0" readbackverify="false" size_in_KB="20.0" sparse="false" start_byte_hex="(4096*NUM_DISK_SECTORS)-20480." start_sector="NUM_DISK_SECTORS-5."/>
</data>
![ba072286-c1f2-4bf9-b886-eff223aa8c94](https://github.com/user-attachments/assets/7d991991-4e52-4bef-8cc5-4887b64ea124)

![e51d0bd2-936c-45bc-9734-f44bab498393](https://github.com/user-attachments/assets/7403ea80-d630-4702-9831-bda9f84378dc)

**Comment by Mingun** [comment]
Please when you post some code use screenshots only in illustrative purposes and always place the text version side by side.

First of all, the problem is not related to the `from_str` method at all. The error from that fact that attributes in Rust types should starts with `@` which is described in the [documentation](https://docs.rs/quick-xml/latest/quick_xml/de/index.html#basics). That is necessary, because in XML you can have both element and attribute with the same name and deserializer should known which one you want to map to the Rust field.
