### ISSUE TITLE
Add support for multi char indentation

### ISSUE THREAD

**Issue by FadyQJ** [tafia/quick-xml#816]
I am creating an xml for use for an external application

The external app will not read the xml I generate unless I do

```rust
let bytes = content.as_bytes();
let mut bytes_new = Vec::<u8>::new();
        
for &byte in bytes {
      if byte == 0x0A {
            bytes_new.push(0x0D);
            bytes_new.push(0x0A);
      } else {
            bytes_new.push(byte);
      }
}

let content = String::from_utf8_lossy(&bytes_new);
```

So from my understanding the app is reading an indentation of two u8 chars instead of one, but there is no option to to so

I am using
`Writer::new_with_indent(Cursor::new(Vec::new()), b' ', 1);`

Edit:
After checking this is equivalent to
`.replace('\n', "\r\n")` 
And I couldn't find any support for `\r\n` it is also hardcoded as `\n`
```rust
pub fn write_indent(&mut self) -> Result<()> {
    if let Some(ref i) = self.indent {
        self.writer.write_all(b"\n")?;
        self.writer.write_all(i.current())?;
    }
    Ok(())
}
```

**Comment by Mingun** [comment]
That can be done with custom writer that will replace each occurrence of `\n` by `\r\n`. Actually, something like this working when you write file in text mode on Windows. When you write `\n` character the runtime actually writes `b'\r\n'` bytes to the "file" (any stream opened in text mode).

I close this issue, because you can implement that by the custom `fmt::Write` implementation, or did postprocess of the whole output, or rely to the runtime library if you writing to files.
