### ISSUE TITLE
How to deserialize a Struct with only Attributes from `BytesStart`?

### ISSUE THREAD

**Issue by C0D3-M4513R** [tafia/quick-xml#824]
I'm currently trying to build a Project, which potentially deals with pretty big xml files.
Other conventional readers/applications (written in other languages) have trouble dealing with those xml files, due to running out of ram.
I want to future proof against the even bigger growing xml files and build a deserializer(/serializer) by using quick_xml's Reader, instead of just reading it all into memory.

However I can find no good solution to actually de-serializing structs, which only have attributes.
(I automatically generate two variants of my structs: one with only attributes and a builder [which is not be important for this issue])

**Comment by Mingun** [comment]
It is unclear, what the troubles you have? Get the [`BytesStart::attributes`](https://docs.rs/quick-xml/latest/quick_xml/events/struct.BytesStart.html#method.attributes) iterator, read attributes and map them to you struct. Something like that:
```rust
struct YourStruct {
  attr1: String,
  attr2: String,
}
match reader.read_event()? {
  Event::Start(start) => {
    let attr1 = None;
    let attr2 = None;
    for attr in start.attributes() {
      match attr.name {
        QName(b"attr1") => attr1 = Some(attr.value),
        QName(b"attr2") => attr2 = Some(attr.value),
        _ => {} // skip unknown attributes
      }
    }
    YourStruct {
      attr1: attr1.unwrap(),
      attr2: attr2.unwrap(),
    }
  }
  _ => {} // other events
}
```

If you want, you may to write a serde deserializer that would deserialize type from the `BytesStart` that will do approximately the same in the `deserialize_map` method. Actually, implementing such deserializer in quick-xml is a good thing for PR.

**Comment by C0D3-M4513R** [comment]
> It is unclear, what the troubles you have? Get the [`BytesStart::attributes`](https://docs.rs/quick-xml/latest/quick_xml/events/struct.BytesStart.html#method.attributes) iterator, read attributes and map them to you struct. Something like that:
> 
> ```rust
> struct YourStruct {
>   attr1: String,
>   attr2: String,
> }
> match reader.read_event()? {
>   Event::Start(start) => {
>     let attr1 = None;
>     let attr2 = None;
>     for attr in start.attributes() {
>       match attr.name {
>         QName(b"attr1") => attr1 = Some(attr.value),
>         QName(b"attr2") => attr2 = Some(attr.value),
>         _ => {} // skip unknown attributes
>       }
>     }
>     YourStruct {
>       attr1: attr1.unwrap(),
>       attr2: attr2.unwrap(),
>     }
>   }
>   _ => {} // other events
> }
> ```
> 
> If you want, you may to write a serde deserializer that would deserialize type from the `BytesStart` that will do approximately the same in the `deserialize_map` method. Actually, implementing such deserializer in quick-xml is a good thing for PR.

The issue is, that the fields are not all strings. Some are integers, some are lists of integers.
Such types are usually handled by quick-xml internally, but I'd have to go ahead and somehow pull out type information reliably with a proc macro and adapt the deserialization strategy based on that, because just naively calling deserialize for each attribute doesn't work:

```
let value: ::quick_xml::events::BytesStart = /*from a reader*/;
let v:Cow<'a, str> = value.try_get_attribute(b"test").unwrap().unwrap();
serde::de::Deserialize::deserialize(::serde::de::IntoDeserializer::<::quick_xml::errors::serialize::DeError>::into_deserializer(v.unescape_value()?))?
```
Errors with `invalid type: string "2016-06-22T19:35:50", expected option` e.g.
or even `invalid type: &str, expected i32.

**Comment by Mingun** [comment]
The deserialization strategy depends on the type. Internally all data in XML represented as `String`. For example, if you want to get `u32`, you call `parse()`:
```rust
let value: ::quick_xml::events::BytesStart = /*from a reader*/;
let value: Cow<str> = value.try_get_attribute(b"test").unwrap().unwrap();
let value: u32 = value.unescape_value()?.parse()?;
```
The same is applicable to the datetime type. Use the type constructor that parses string representation in desired format. You do not need to deal with serde-support types from quick-xml at all.

The [`IntoDeserializer for String`](https://docs.rs/serde/latest/serde/de/trait.IntoDeserializer.html#impl-IntoDeserializer%3C'de,+E%3E-for-String) returns a deserializer that almost always provides a string input to the types, it does not convert types for you (the one exception is enums where string converted to unit variant of enum). Conversion from internal representation (`String` in case of XML) to the desired _primitive_ type is the responsibility of a deserializer of a concrete type format (quick-xml's deserializers in that case). For attributes quick-xml uses `quick_xml::de::SimpleTypeDeserializer`, which, as I noted, currently is private, but it can be made public and actually I always wanted that it will public. This will be fixed in next release.

**Comment by C0D3-M4513R** [comment]
Thank you so much for that tip with the `SimpleTypeDeserializer`. I've created a pr to make that struct public.
