### ISSUE TITLE
escaping BytesText does not does not work in 0.10

### ISSUE THREAD

**Issue by alex-shapiro** [tafia/quick-xml#99]
The `BytesText::escaped` function no longer escapes in 0.10. The problem stems from the following change in #96: https://github.com/tafia/quick-xml/pull/96/files#diff-8fa47ebb5ed7bcd20efc67fa222b62aaL344

**Comment by tafia** [comment]
Can you be more specific?
Do you have an example that doesn't work.

cc @andy128k 

Since this PR, we consider that the content is **always** escaped. 

When building the events, it manages `S: AsRef<str>` and `&[u8]` differently: [the former](https://github.com/tafia/quick-xml/pull/96/files#diff-8fa47ebb5ed7bcd20efc67fa222b62aaR324) will be escaped while [the](https://github.com/tafia/quick-xml/pull/96/files#diff-8fa47ebb5ed7bcd20efc67fa222b62aaR316) [latter](https://github.com/tafia/quick-xml/pull/96/files#diff-8fa47ebb5ed7bcd20efc67fa222b62aaR308) won't .

This is nice because when modifying a file (which is escaped), we don't care about escaping/unescaping: we just want to push the same raw bytes everywhere except on the part we are modifying.

When building an entirely new file on the contrary, we usually use utf8 and it is nice to just be able to use `from_str`.

As for why the `escaped` function in particular exists, it is mainly for symmetry with the `unescaped` one. It abstract the technical implementation details.

Granted, we could do better on documentation.

**Comment by andy128k** [comment]
@alex-shapiro The idea behind those changes is to bring symmetry to library's API. You still can consume text nodes and pass through to a writer (this is what `encoded` does, it gives raw, encoded bytes), but also you can decode, process and encode back a text (`unescape_and_decode` and `from_str` are made for this).

The change, you've mentioned (and some changes before) are made to bring this distinction between raw bytes and decoded data.

It looks like your issue is similar to an issue `rss` had (https://github.com/rust-syndication/rss/pull/64/files).

**Comment by andy128k** [comment]
@tafia I had an idea to wrap [u8]'s in opaque structs to prevent mixture of escaped and unescaped bytes on type level. But this will definitely break whole API's surface.

**Comment by tafia** [comment]
> @tafia I had an idea to wrap [u8]'s in opaque structs to prevent mixture of escaped and unescaped bytes on type level. But this will definitely break whole API's surface.

I understand the rationale. At the same time, I like being transparent on what is done and why. I believe a good documentation will be better here to avoid these issues.
